### ISSUE TITLE
infer Error

### ISSUE THREAD

**Issue by redstarxz** [ykdai/BasicPBC#1]
Traceback (most recent call last):
  File "D:\BasicPBC\basicsr\test.py", line 45, in <module>
    test_pipeline(root_path)
  File "D:\BasicPBC\basicsr\test.py", line 35, in test_pipeline
    model = build_model(opt)
  File "d:\basicpbc\basicsr\models\__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt["model_type"])(opt)
  File "d:\basicpbc\basicsr\models\sr_model.py", line 30, in __init__
    self.load_network(self.net_g, load_path, self.opt["path"].get("strict_load_g", True), param_key)
  File "d:\basicpbc\basicsr\models\base_model.py", line 292, in load_network
    load_net = load_net[param_key]
KeyError: 'params_ema'

**Comment by toyxyz** [comment]
Same here!

Traceback (most recent call last):
  File "C:\Users\toyxy\BasicPBC\basicsr\test.py", line 45, in <module>
    test_pipeline(root_path)
  File "C:\Users\toyxy\BasicPBC\basicsr\test.py", line 35, in test_pipeline
    model = build_model(opt)
  File "c:\users\toyxy\basicpbc\basicsr\models\__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt["model_type"])(opt)
  File "c:\users\toyxy\basicpbc\basicsr\models\sr_model.py", line 30, in __init__
    self.load_network(self.net_g, load_path, self.opt["path"].get("strict_load_g", True), param_key)
  File "c:\users\toyxy\basicpbc\basicsr\models\base_model.py", line 292, in load_network
    load_net = load_net[param_key]
KeyError: 'params_ema'

**Comment by ykdai** [comment]
Thank you so much for the feedback. We have updated the checkpoint to avoid this KeyError. Please download the latest checkpoint for inference.
