### ISSUE TITLE
BasicPBC cannot be executed.

### ISSUE THREAD

**Issue by la-darknesss** [ykdai/BasicPBC#10]
I followed the instructions in Readme.md and attempted to execute BasicPBC. Two errors occurred:

1. I executed `pip install torch-scatter`.
```
ModuleNotFoundError: No module named 'torch_scatter'
```

2. I don't know how to resolve the issue. Please provide the cause and solution.
```
Length of Testing Sequence is  2990
2024-04-09 20:54:18,673 INFO: Dataset [PaintBucketSegMat] - PaintBucket_Char is built.
2024-04-09 20:54:18,674 INFO: Number of test images in PaintBucket_Char: 2990
Traceback (most recent call last):
  File "D:\BasicPBC\basicsr\test.py", line 45, in <module>
    test_pipeline(root_path)
  File "D:\BasicPBC\basicsr\test.py", line 35, in test_pipeline
    model = build_model(opt)
  File "d:\basicpbc\basicsr\models\__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt["model_type"])(opt)
  File "d:\basicpbc\basicsr\models\sr_model.py", line 22, in __init__
    self.net_g = build_network(opt["network_g"])
  File "d:\basicpbc\basicsr\archs\__init__.py", line 22, in build_network
    net = ARCH_REGISTRY.get(network_type)(**opt)
TypeError: BasicPBC.__init__() got an unexpected keyword argument 'sinkhorn_iterations'
```

Thank you.

**Comment by dienachtderwelt** [comment]
Hi thank you for your feedback. For `2` please pull the newest repo. It's caused by an inconsistency after a recent update and is fixed now. Sorry for the inconvenience.

**Comment by la-darknesss** [comment]
Thank you for your assistance.
The BasicPBC has been successfully executed.
I appreciate your help.
